### ISSUE TITLE
Issue cloning the document

### ISSUE THREAD

**Issue by ibammad00** [shaw8wit/Auction#1]
Hi!
I tried cloning this document but there's a slight issue.
I have changed the names of your directory "commerce" and "auctions." I have made sure that these changes are reflected throughout the code.

However, when I try to runserver it shows the following error: "Template Does not exist." I have checked in views and the name of HTML file and directory it is are consistent. Yet, it cannot find the file

![image](https://user-images.githubusercontent.com/87228899/125161155-28c2cb80-e19a-11eb-8019-abe9f5b9f2f1.png)

Kindly guide me how can I make it work.

**Comment by shaw8wit** [comment]
@ibammad00 hello sorry for the late response, hopefully, you've found the error.
If not then do check this discussion out. 
[https://stackoverflow.com/questions/18293875/easy-way-to-rename-a-django-project](url)
